/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelos.Videojuego;

/**
 *
 * @author gemrx
 */
public class Main extends javax.swing.JFrame {
    File selectedFile = null;
    byte[] imagenBytes = null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        pagina2Id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dashboard = new javax.swing.JPanel();
        buttonTabInsertar = new javax.swing.JButton();
        buttonTabModificar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pagina1 = new javax.swing.JPanel();
        pagina1FechaLanzamiento = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        pagina1Desarrollador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pagina1Titulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pagina1LabelImagen = new javax.swing.JLabel();
        buttonSeleccionarImagen = new javax.swing.JButton();
        buttonInsertar = new javax.swing.JButton();
        pagina2 = new javax.swing.JPanel();
        buttonActualizar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        pagina2FechaLanzamiento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        pagina2Desarrollador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pagina2Titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        ButtonSeleccionarImagen2 = new javax.swing.JButton();
        pagina2LabelImagen = new javax.swing.JLabel();
        pagina2Id = new javax.swing.JLabel();
        buttonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setBackground(new java.awt.Color(130, 143, 180));

        buttonTabInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonTabInsertar.setText("Insertar");
        buttonTabInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabInsertarActionPerformed(evt);
            }
        });

        buttonTabModificar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonTabModificar.setText("Modificar");
        buttonTabModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTabModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonTabInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTabModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(buttonTabInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonTabModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        getContentPane().add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 405));

        pagina1FechaLanzamiento.setDateFormatString("yyyy-MM-dd");
        pagina1FechaLanzamiento.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de Lanzamiento");

        pagina1Desarrollador.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pagina1Desarrollador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina1DesarrolladorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Desarrollador");

        pagina1Titulo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pagina1Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina1TituloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Titulo");

        pagina1LabelImagen.setBackground(new java.awt.Color(153, 153, 255));
        pagina1LabelImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonSeleccionarImagen.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonSeleccionarImagen.setText("Seleccionar Imagen");
        buttonSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeleccionarImagenActionPerformed(evt);
            }
        });

        buttonInsertar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonInsertar.setText("Insertar");
        buttonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagina1Layout = new javax.swing.GroupLayout(pagina1);
        pagina1.setLayout(pagina1Layout);
        pagina1Layout.setHorizontalGroup(
            pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagina1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pagina1FechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pagina1Titulo)
                        .addComponent(pagina1Desarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagina1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(buttonSeleccionarImagen))
                    .addComponent(pagina1LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        pagina1Layout.setVerticalGroup(
            pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagina1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pagina1LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pagina1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagina1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagina1Desarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagina1FechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(buttonInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", pagina1);

        buttonActualizar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonActualizar.setText("Actualizar");
        buttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });

        buttonEliminar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        pagina2FechaLanzamiento.setDateFormatString("yyyy-MM-dd");
        pagina2FechaLanzamiento.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de Lanzamiento");

        pagina2Desarrollador.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pagina2Desarrollador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina2DesarrolladorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Desarrollador");

        pagina2Titulo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        pagina2Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina2TituloActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Titulo");

        buttonBuscar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        ButtonSeleccionarImagen2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ButtonSeleccionarImagen2.setText("Seleccionar Imagen");
        ButtonSeleccionarImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSeleccionarImagen2ActionPerformed(evt);
            }
        });

        pagina2LabelImagen.setBackground(new java.awt.Color(153, 153, 255));
        pagina2LabelImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        pagina2Id.setText("Label ID Invisible (NO CAMBIAR)");

        buttonImprimir.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        buttonImprimir.setText("Imprimir");
        buttonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagina2Layout = new javax.swing.GroupLayout(pagina2);
        pagina2.setLayout(pagina2Layout);
        pagina2Layout.setHorizontalGroup(
            pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagina2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagina2Layout.createSequentialGroup()
                        .addComponent(pagina2Id, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pagina2Layout.createSequentialGroup()
                        .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pagina2Layout.createSequentialGroup()
                                .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagina2FechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagina2Titulo)
                                    .addComponent(pagina2Desarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonBuscar))
                            .addGroup(pagina2Layout.createSequentialGroup()
                                .addComponent(buttonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pagina2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pagina2Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(ButtonSeleccionarImagen2))
                            .addComponent(pagina2LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        pagina2Layout.setVerticalGroup(
            pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagina2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pagina2Id)
                .addGap(18, 18, 18)
                .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagina2Layout.createSequentialGroup()
                        .addComponent(pagina2LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSeleccionarImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pagina2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pagina2Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonBuscar))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagina2Desarrollador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pagina2FechaLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", pagina2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, -35, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTabInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTabInsertarActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_buttonTabInsertarActionPerformed

    private void buttonTabModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTabModificarActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_buttonTabModificarActionPerformed

    private void pagina1TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina1TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina1TituloActionPerformed

    private void pagina1DesarrolladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina1DesarrolladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina1DesarrolladorActionPerformed

    private void buttonSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeleccionarImagenActionPerformed
        // Configurar el selector de archivos
        JFileChooser fileChooser =  new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Imagenes", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setFileFilter(imageFilter);
        
        // Abrir el selector de archivos
        int result = fileChooser.showOpenDialog(this);
        
        // Si no ocurrió ningún error y se seleccionó un archivo
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            
            // Cargar la imagen seleccionada en un ImageIcon
            ImageIcon originalImageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            
            // Escalar la imagen al tamaño del JLabel
            Image originalImage = originalImageIcon.getImage();
            Image scaledImage = originalImage.getScaledInstance(pagina1LabelImagen.getWidth(), pagina1LabelImagen.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
            pagina1LabelImagen.setIcon(scaledImageIcon);
        }
    }//GEN-LAST:event_buttonSeleccionarImagenActionPerformed

    private byte[] obtenerBytesDesdeImagen(File archivoImagen) {
        try {
            // Verificar si el archivo existe y es una imagen
            if (archivoImagen != null && archivoImagen.exists() && esImagen(archivoImagen)) {
                // Leer el archivo de la imagen y convertirlo a un arreglo de bytes
                FileInputStream fis = new FileInputStream(archivoImagen);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte[] buffer = new byte[1024];
                int bytesRead;

                while ((bytesRead = fis.read(buffer)) != -1) {
                    bos.write(buffer, 0, bytesRead);
                }

                byte[] imagenEnBytes = bos.toByteArray();

                // Cerrar streams
                bos.close();
                fis.close();

                return imagenEnBytes;
            } else {
                // Manejo de casos en los que el archivo no es válido o no es una imagen
                return null;
            }
        } catch (IOException e) {
            System.out.println("No se pudo obtener los bytes de la imagen seleccionada");
            return null;
        }
    }
    
    private boolean esImagen(File archivo) {
        String nombreArchivo = archivo.getName().toLowerCase();
        return nombreArchivo.endsWith(".jpg") || nombreArchivo.endsWith(".jpeg") ||
               nombreArchivo.endsWith(".png") || nombreArchivo.endsWith(".gif");
    }
    
    private void buttonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertarActionPerformed
        Videojuego nuevoJuego = new Videojuego();
        nuevoJuego.setTitulo(pagina1Titulo.getText());
        nuevoJuego.setDesarrollador(pagina1Desarrollador.getText());
        nuevoJuego.setImagen(obtenerBytesDesdeImagen(selectedFile));
        
        // setear la fecha de lanzamiento
        Date selectedDate = pagina1FechaLanzamiento.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Cambia el formato según tus necesidades
        String formattedDate = dateFormat.format(selectedDate);
        nuevoJuego.setFechaLanzamiento(formattedDate);
        
        // insertar el juego
        if (nuevoJuego.insertar()) {
            JOptionPane.showMessageDialog(this, "El juego ha sido insertado correctamente.", "Insercion Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error tratar de insertar el juego. Inténtalo de nuevo.", "Error de Insercion", JOptionPane.ERROR_MESSAGE);
        }
        
        // Limpiar campos
        selectedFile = null;
        imagenBytes = null;
        pagina1Titulo.setText("");
        pagina1LabelImagen.setIcon(null);
        pagina1Desarrollador.setText("");
        pagina1FechaLanzamiento.setDate(null);
    }//GEN-LAST:event_buttonInsertarActionPerformed

    private void pagina2TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina2TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina2TituloActionPerformed

    private void pagina2DesarrolladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina2DesarrolladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina2DesarrolladorActionPerformed

    private void ButtonSeleccionarImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSeleccionarImagen2ActionPerformed
        // Configurar el selector de archivos
        JFileChooser fileChooser =  new JFileChooser();
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Imagenes", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setFileFilter(imageFilter);
        
        // Abrir el selector de archivos
        int result = fileChooser.showOpenDialog(this);
        
        // Si no ocurrió ningún error y se seleccionó un archivo
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            
            // Cargar la imagen seleccionada en un ImageIcon
            ImageIcon originalImageIcon = new ImageIcon(selectedFile.getAbsolutePath());
            
            // Escalar la imagen al tamaño del JLabel
            Image originalImage = originalImageIcon.getImage();
            Image scaledImage = originalImage.getScaledInstance(pagina2LabelImagen.getWidth(), pagina1LabelImagen.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
            pagina2LabelImagen.setIcon(scaledImageIcon);
        }
    }//GEN-LAST:event_ButtonSeleccionarImagen2ActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        Videojuego juegoAModificar = new Videojuego();
        juegoAModificar.setId(Integer.parseInt(pagina2Id.getText()));
        juegoAModificar.setTitulo(pagina2Titulo.getText());
        
        if (selectedFile !=  null) {
            juegoAModificar.setImagen(obtenerBytesDesdeImagen(selectedFile));
        } else {
            juegoAModificar.setImagen(imagenBytes);
        }
        
        juegoAModificar.setDesarrollador(pagina2Desarrollador.getText());
        
        Date selectedDate = pagina2FechaLanzamiento.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Cambia el formato según tus necesidades
        String formattedDate = dateFormat.format(selectedDate);
        juegoAModificar.setFechaLanzamiento(formattedDate);
        
        if (juegoAModificar.actualizar()) {
            JOptionPane.showMessageDialog(this, "El juego ha sido actualizado correctamente.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el juego. Inténtalo de nuevo.", "Error de Actualización", JOptionPane.ERROR_MESSAGE);
        }
        
        // Limpiar campos
        selectedFile = null;
        imagenBytes = null;
        pagina2Id.setText("");
        pagina2Titulo.setText("");
        pagina2LabelImagen.setIcon(null);
        pagina2Desarrollador.setText("");
        pagina2FechaLanzamiento.setDate(null);
    }//GEN-LAST:event_buttonActualizarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        Videojuego juegoAEliminar = new Videojuego();
        juegoAEliminar.setId(Integer.parseInt(pagina2Id.getText()));
        
        if (juegoAEliminar.eliminar()) {
            JOptionPane.showMessageDialog(this, "El juego ha sido eliminado correctamente.", "Eliminacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Error tratar de eliminar el juego. Inténtalo de nuevo.", "Error de Eliminacion", JOptionPane.ERROR_MESSAGE);
        }
        
        // Limpiar campos
        selectedFile = null;
        imagenBytes = null;
        pagina2Id.setText("");
        pagina2Titulo.setText("");
        pagina2LabelImagen.setIcon(null);
        pagina2Desarrollador.setText("");
        pagina2FechaLanzamiento.setDate(null);
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        Videojuego juegoObtenido = Videojuego.obtenerVideojuegoPorTitulo(pagina2Titulo.getText());
        
        if (juegoObtenido ==  null) {
             JOptionPane.showMessageDialog(this, "No se econtro ningun juego con ese nombre. Intentalo de nuevo", "Juego No Encontrado", JOptionPane.ERROR_MESSAGE);
             selectedFile = null;
             imagenBytes = null;
             pagina2Id.setText("");
             pagina2Titulo.setText("");
             pagina2LabelImagen.setIcon(null);
             pagina2Desarrollador.setText("");
             pagina2FechaLanzamiento.setDate(null);
             return;
        }
        
        pagina2Id.setText(String.valueOf(juegoObtenido.getId()));
        pagina2Titulo.setText(juegoObtenido.getTitulo());
        
        imagenBytes = juegoObtenido.getImagen();
        if (imagenBytes != null && imagenBytes.length > 0) {
            ImageIcon originalIcon = new ImageIcon(imagenBytes); // Crea un ImageIcon original
            
            // Escalar la imagen al tamaño del JLabel
            Image imagenEscalada = originalIcon.getImage().getScaledInstance(
                pagina2LabelImagen.getWidth(), pagina2LabelImagen.getHeight(), Image.SCALE_SMOOTH);

            // Crear un nuevo ImageIcon con la imagen escalada
            ImageIcon imageIconEscalado = new ImageIcon(imagenEscalada);

            // Establecer el ImageIcon escalado en el JLabel (pagina2LabelImagen)
            pagina2LabelImagen.setIcon(imageIconEscalado);
        }
        
        pagina2Desarrollador.setText(juegoObtenido.getDesarrollador());
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Date fecha = dateFormat.parse(juegoObtenido.getFechaLanzamiento());
            pagina2FechaLanzamiento.setDate(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImprimirActionPerformed
        printPanel(pagina2);
    }//GEN-LAST:event_buttonImprimirActionPerformed

    private void printPanel(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Panel");

        printerJob.setPrintable(new Printable() {
            public int print(Graphics g, PageFormat pf, int pageIndex) {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D) g;
                g2.translate(pf.getImageableX(), pf.getImageableY());

                // You can adjust the width and height of the panel
                panel.setSize(panel.getPreferredSize());
                panel.print(g2);

                return Printable.PAGE_EXISTS;
            }
        });

        boolean ok = printerJob.printDialog();
        if (ok) {
            try {
                printerJob.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSeleccionarImagen2;
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonImprimir;
    private javax.swing.JButton buttonInsertar;
    private javax.swing.JButton buttonSeleccionarImagen;
    private javax.swing.JButton buttonTabInsertar;
    private javax.swing.JButton buttonTabModificar;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pagina1;
    private javax.swing.JTextField pagina1Desarrollador;
    private com.toedter.calendar.JDateChooser pagina1FechaLanzamiento;
    private javax.swing.JLabel pagina1LabelImagen;
    private javax.swing.JTextField pagina1Titulo;
    private javax.swing.JPanel pagina2;
    private javax.swing.JTextField pagina2Desarrollador;
    private com.toedter.calendar.JDateChooser pagina2FechaLanzamiento;
    private javax.swing.JLabel pagina2Id;
    private javax.swing.JLabel pagina2LabelImagen;
    private javax.swing.JTextField pagina2Titulo;
    // End of variables declaration//GEN-END:variables
}
